#!/usr/bin/with-contenv bash

echo "-------------------------------------"
# AiKore specific permissions
echo "Ensuring AiKore has ownership of necessary directories..."
mkdir -p /etc/nginx/locations.d
chown -R abc:abc /etc/nginx/locations.d
# Create and permit the directory for NGINX reload flags
mkdir -p /run/aikore
chown -R abc:abc /run/aikore
echo "Done."

# General permissions
echo "chown'ing home directory to ensure correct permissions."
find /home/abc -type d \( ! -user abc -o ! -group abc \) -exec chown -R abc:abc {} \;
find /home/abc -type f \( ! -user abc -o ! -group abc \) -exec chown abc:abc {} \;
echo "Done!"
echo -e "-------------------------------------\n"

# Reset rights if the reset-flag file isn't present
if [ ! -f "$BASE_DIR/Delete_this_file_to_reset_access_rights_at_next_launch" ]; then
    echo "-------------------------------------"
    echo "chown'ing main config directory to ensure correct permissions."
    mkdir -p $BASE_DIR/models $BASE_DIR/outputs
    chown -R abc:users $BASE_DIR
    chmod -R 774 $BASE_DIR
    chmod -R 664 $BASE_DIR/models
    chmod -R 664 $BASE_DIR/outputs
    find $BASE_DIR -type d -exec chmod 777 {} +
    echo "Delete this file to reset access rights at next launch" > "$BASE_DIR/Delete_this_file_to_reset_access_rights_at_next_launch"
    echo "Done!"
    echo -e "-------------------------------------\n"
fi