from pydantic import BaseModel

# --- Base Schema ---
# Defines the common attributes for an instance, used for creation and reading.
class InstanceBase(BaseModel):
    name: str
    base_blueprint: str
    gpu_ids: str | None = None
    autostart: bool = False
    persistent_mode: bool = False
    hostname: str | None = None # NEW: Add hostname field
    use_custom_hostname: bool = False

# --- Creation Schema ---
# Inherits from Base and is used specifically when creating a new instance via the API.
class InstanceCreate(InstanceBase):
    port: int | None = None

# --- Update Schema ---
# Defines the fields that are allowed to be updated on an existing instance.
class InstanceUpdate(BaseModel):
    name: str | None = None
    base_blueprint: str | None = None # <-- MODIFICATION ICI
    gpu_ids: str | None = None
    autostart: bool | None = None
    hostname: str | None = None
    use_custom_hostname: bool | None = None

# --- Read Schema ---
# This schema is used when returning instance data from the API.
# It includes attributes that are generated by the database (like `id` and `status`).
class Instance(InstanceBase):
    id: int
    status: str
    pid: int | None = None
    port: int | None = None
    persistent_port: int | None = None
    persistent_display: int | None = None

    class Config:
        # This tells Pydantic to read the data even if it is not a dict,
        # but an ORM model (like our SQLAlchemy model).
        from_attributes = True